name: active_learning_dd
channels:
- bioconda
- rdkit
- conda-forge
- default
dependencies:
- python=3.6
- rdkit=2018.03.4.0
- pandas=0.23.4
- matplotlib=2.2.3
- tensorflow=1.11.0
- keras=2.2.4
- scikit-learn=0.19.2
- pubchempy=1.0.4