name: Test active learning in drug discovery

on:
- push
- pull_request
jobs:
  Test:
    name: Test active learning in drug discovery
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: active_learning_dd
          environment-file: conda_cpu_env.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      # Log conda environment contents
      - name: Log conda environment
        shell: bash --login {0}
        run: conda list
      # Activate the installed packages
      - name: Install active_learning_dd package
        shell: bash --login {0}
        run: pip install -e .
    # Test Sample Runner
      - name: Test sample data runner
        shell: bash --login {0}
        run: |
          cd chtc_runners
          python sample_data_runner.py \
            --pipeline_params_json_file=../param_configs/sample_data_config.json \
            --hyperparams_json_file=../param_configs/experiment_PstP_hyperparams/sampled_hyparams/ClusterBasedWCSelector_609.json \
            --iter_max=5 \
            --no-precompute_dissimilarity_matrix \
            --initial_dataset_file=../datasets/sample_data/training_data/iter_0.csv.gz
   # Tests the BT clustering
      - name: Test BT_Clustering
        shell: bash --login {0}
        run: |
          cd active_learning_dd/utils
          python generate_bt_clustering.py --csv_file_or_dir=./sample_data/unlabeled_data/unlabeled_0.csv --output_dir=./tmp_test --feature_name="Morgan FP_2_1024" --cutoff=0.4
    # Tests that base Simulation Runner
      - name: Test Simulation Runner
        shell: bash --login {0}
        run: python chtc_runners/simulation_runner.py --pipeline_params_json_file=param_configs/sample_data_config.json --nbs_params_json_file=param_configs/ClusterBasedWCSelector_params_reduced.json --exploration_strategy=weighted --iter_max=5 --process_num=0 --batch_size_index=0 --rnd_seed=0 --no-random_param_sampling --precompute_dissimilarity_matrix
